wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.16
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: examples._type
      5: 1
      6:
      - 1
    - 1: examples.width
      5: 1
      6:
      - 1
    - 1: examples.height
      5: 1
      6:
      - 1
    - 1: examples.format
      5: 1
      6:
      - 1
    - 1: examples.count
      5: 1
      6:
      - 1
    - 1: examples.filenames
      5: 1
      6:
      - 1
    - 1: examples.captions
      5: 1
      6:
      - 1
    - 1: train_loss_step
      5: 1
      6:
      - 1
    - 1: train_acc_step
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    - 1: val_loss
      5: 1
      6:
      - 1
    - 1: val_acc
      5: 1
      6:
      - 1
    - 1: train_loss_epoch
      5: 1
      6:
      - 1
    - 1: train_acc_epoch
      5: 1
      6:
      - 1
    python_version: 3.9.13
    start_time: 1664541655
    t:
      1:
      - 1
      - 9
      - 41
      - 55
      2:
      - 1
      - 9
      - 41
      - 55
      3:
      - 7
      4: 3.9.13
      5: 0.12.16
      8:
      - 3
      - 5
input_shape:
  desc: null
  value:
  - 3
  - 32
  - 32
learning_rate:
  desc: null
  value: 0.0002
num_classes:
  desc: null
  value: 10
